name = "TerminalClock"
uuid = "65687e93-20ea-45b9-bbc3-ed39219e1d43"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]