[Large]

zero = [
" <-----> ",
"^       ^",
"|       |",
"v       v",
"         ",
"^       ^",
"|       |",
"v       v",
" <-----> ",
]

one = [
"         ",
"        ^",
"        |",
"        v",
"         ",
"        ^",
"        |",
"        v",
"         ",
]

two = [
" <-----> ",
"        ^",
"        |",
"        v",
" <-----> ",
"^        ",
"|        ",
"v        ",
" <-----> ",
]

three = [
" <-----> ",
"        ^",
"        |",
"        v",
" <-----> ",
"        ^",
"        |",
"        v",
" <-----> ",
]

four = [
"         ",
"^       ^",
"|       |",
"v       v",
" <-----> ",
"        ^",
"        |",
"        v",
"         ",
]

five = [
" <-----> ",
"^        ",
"|        ",
"v        ",
" <-----> ",
"        ^",
"        |",
"        v",
" <-----> ",
]

six =[
" <-----> ",
"^        ",
"|        ",
"v        ",
" <-----> ",
"^       ^",
"|       |",
"v       v",
" <-----> ",
]

seven = [
" <-----> ",
"        ^",
"        |",
"        v",
"         ",
"        ^",
"        |",
"        v",
"         ",
]

eight = [
" <-----> ",
"^       ^",
"|       |",
"v       v",
" <-----> ",
"^       ^",
"|       |",
"v       v",
" <-----> ",
]

nine = [
" <-----> ",
"^       ^",
"|       |",
"v       v",
" <-----> ",
"        ^",
"        |",
"        v",
" <-----> ",
]

colon = [
"         ",
"         ",
"    ⊗    ",
"         ",
"         ",
"         ",
"    ⊗    ",
"         ",
"         ",
]

[Small]

zero = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"|   |",
"     ",
"|   |",
" --- ",
]

one = [
"     ",
"     ",
"     ",
"     ",
"     ",
"    |",
"     ",
"    |",
"     ",
]

two = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"    |",
" --- ",
"|    ",
" --- ",
]

three = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"    |",
" --- ",
"    |",
" --- ",
]

four = [
"     ",
"     ",
"     ",
"     ",
"     ",
"|   |",
" --- ",
"    |",
"     ",
]

five = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"|    ",
" --- ",
"    |",
" --- ",
]

six =[
"     ",
"     ",
"     ",
"     ",
" --- ",
"|    ",
" --- ",
"|   |",
" --- ",
]

seven = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"    |",
"     ",
"    |",
"    ",
]

eight = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"|   |",
" --- ",
"|   |",
" --- ",
]

nine = [
"     ",
"     ",
"     ",
"     ",
" --- ",
"|   |",
" --- ",
"    |",
" --- ",
]

colon = [
"     ",
"     ",
"     ",
"     ",
"     ",
"  ⊗  ",
"     ",
"  ⊗  ",
"     ",
]