[Large]

zero = [
"+-------+",
"|       |",
"|       |",
"|       |",
"+       +",
"|       |",
"|       |",
"|       |",
"+-------+",
]

one = [
"        +",
"        |",
"        |",
"        |",
"        +",
"        |",
"        |",
"        |",
"        +",
]

two = [
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
"|        ",
"|        ",
"|        ",
"+-------+",
]

three = [
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
]

four = [
"+       +",
"|       |",
"|       |",
"|       |",
"+-------+",
"        |",
"        |",
"        |",
"        +",
]

five = [
"+-------+",
"|        ",
"|        ",
"|        ",
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
]

six =[
"+-------+",
"|        ",
"|        ",
"|        ",
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
]

seven = [
"+-------+",
"        |",
"        |",
"        |",
"        +",
"        |",
"        |",
"        |",
"        +",
]

eight = [
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
]

nine = [
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
]

colon = [
"         ",
"         ",
"    ⊗    ",
"         ",
"         ",
"         ",
"    ⊗    ",
"         ",
"         ",
]

[Medium]

zero = [
"+-------+",
"|       |",
"|       |",
"|       |",
"+       +",
"|       |",
"|       |",
"|       |",
"+-------+",
]

one = [
"        +",
"        |",
"        |",
"        |",
"        +",
"        |",
"        |",
"        |",
"        +",
]

two = [
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
"|        ",
"|        ",
"|        ",
"+-------+",
]

three = [
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
]

four = [
"+       +",
"|       |",
"|       |",
"|       |",
"+-------+",
"        |",
"        |",
"        |",
"        +",
]

five = [
"+-------+",
"|        ",
"|        ",
"|        ",
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
]

six =[
"+-------+",
"|        ",
"|        ",
"|        ",
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
]

seven = [
"+-------+",
"        |",
"        |",
"        |",
"        +",
"        |",
"        |",
"        |",
"        +",
]

eight = [
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
]

nine = [
"+-------+",
"|       |",
"|       |",
"|       |",
"+-------+",
"        |",
"        |",
"        |",
"+-------+",
]

colon = [
"         ",
"         ",
"    ⊗    ",
"         ",
"         ",
"         ",
"    ⊗    ",
"         ",
"         ",
]

[Small]

zero = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"|   |",
"+   +",
"|   |",
"+---+",
]

one = [
"     ",
"     ",
"     ",
"     ",
"    +",
"    |",
"    +",
"    |",
"    +",
]

two = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"    |",
"+---+",
"|    ",
"+---+",
]

three = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"    |",
"+---+",
"    |",
"+---+",
]

four = [
"     ",
"     ",
"     ",
"     ",
"+   +",
"|   |",
"+---+",
"    |",
"    +",
]

five = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"|    ",
"+---+",
"    |",
"+---+",
]

six =[
"     ",
"     ",
"     ",
"     ",
"+---+",
"|    ",
"+---+",
"|   |",
"+---+",
]

seven = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"    |",
"    +",
"    |",
"    +",
]

eight = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"|   |",
"+---+",
"|   |",
"+---+",
]

nine = [
"     ",
"     ",
"     ",
"     ",
"+---+",
"|   |",
"+---+",
"    |",
"+---+",
]

colon = [
"     ",
"     ",
"     ",
"     ",
"     ",
"  ⊗  ",
"     ",
"  ⊗  ",
"     ",
]