# UnicodeBox.toml
# Based on cormullion-san's idea
# https://github.com/AtelierArith/TerminalClock.jl/issues/16#issuecomment-974051666

[Large]
zero = [
" ▒█████▒ ",
" ██   ██ ",
"██     ██",
"█       █",
"█       █",
"█       █",
"██     ██",
" ██   ██ ",
" ▒█████▒ ",
]

one = [
"    ░█   ",
"   ███   ",
"    ██   ",
"    ██   ",
"    ██   ",
"    ██   ",
"    ██   ",
"    ██   ",
"   ████  ",
]

two = [
" ░█████░ ",
" ██   ██░",
"      ██ ",
"     ██  ",
"    ██   ",
"   ██    ",
"  ██     ",
" ██░     ",
" ███████ ",
]

three = [
" ░██████ ",
" ██   ███",
"       ██",
"      ░█░",
"   █████ ",
"      ░█░",
"       ██",
" ██    ██",
" ░██████ ",
]

four = [
"     ░██ ",
"    ████ ",
"   ██ ██ ",
"  ██  ██ ",
" ██   ██ ",
"██    ██ ",
"█████████",
"      ██ ",
"      ██ ",
]

five = [
" ███████ ",
" ██      ",
"▒██      ",
"██       ",
"████████░",
"       ██",
"       ██",
"██     ██",
" ███████░",
]

six = [
"  █████  ",
" ██   ██ ",
" ██      ",
"██       ",
"████████ ",
"██     ██",
"█       █",
"███   ███",
"  █████  ",
]

seven = [
"█████████",
"       ██",
"      ██ ",
"      ██ ",
"    ███  ",
"    ██   ",
"  ███    ",
"  ██     ",
"  ██     ",
]

eight = [
"  ▒███▒  ",
" ██   ██ ",
"██     ██",
" ██   ██ ",
"  █████  ",
" █     █ ",
"██     ██",
"█       █",
"▒███████▒",
]

nine = [
" ▒█████▒ ",
" ██    ██",
"██      █",
" ██    ██",
"  ███████",
"       ██",
"      ██ ",
" ██  ██  ",
"  ████▒  ",
]

colon = [
"         ",
"   ▒█▒   ",
"   ███   ",
"   ▒█▒   ",
"         ",
"   ▒█▒   ",
"   ███   ",
"   ▒█▒   ",
"         ",
]

[Small]
zero = [
" ▒█████▒ ",
" ██   ██ ",
"██     ██",
"█       █",
"█       █",
"█       █",
"██     ██",
" ██   ██ ",
" ▒█████▒ ",
]

one = [
"    ░█   ",
"   ███   ",
"    ██   ",
"    ██   ",
"    ██   ",
"    ██   ",
"    ██   ",
"    ██   ",
"   ████  ",
]

two = [
" ░█████░ ",
" ██   ██░",
"      ██ ",
"     ██  ",
"    ██   ",
"   ██    ",
"  ██     ",
" ██░     ",
" ███████ ",
]

three = [
" ░██████ ",
" ██   ███",
"       ██",
"      ░█░",
"   █████ ",
"      ░█░",
"       ██",
" ██    ██",
" ░██████ ",
]

four = [
"     ░██ ",
"    ████ ",
"   ██ ██ ",
"  ██  ██ ",
" ██   ██ ",
"██    ██ ",
"█████████",
"      ██ ",
"      ██ ",
]

five = [
" ███████ ",
" ██      ",
"▒██      ",
"██       ",
"████████░",
"       ██",
"       ██",
"██     ██",
" ███████░",
]

six = [
"  █████  ",
" ██   ██ ",
" ██      ",
"██       ",
"████████ ",
"██     ██",
"█       █",
"███   ███",
"  █████  ",
]

seven = [
"█████████",
"       ██",
"      ██ ",
"      ██ ",
"    ███  ",
"    ██   ",
"  ███    ",
"  ██     ",
"  ██     ",
]

eight = [
"  ▒███▒  ",
" ██   ██ ",
"██     ██",
" ██   ██ ",
"  █████  ",
" █     █ ",
"██     ██",
"█       █",
"▒███████▒",
]

nine = [
" ▒█████▒ ",
" ██    ██",
"██      █",
" ██    ██",
"  ███████",
"       ██",
"      ██ ",
" ██  ██  ",
"  ████▒  ",
]

colon = [
"         ",
"   ▒█▒   ",
"   ███   ",
"   ▒█▒   ",
"         ",
"   ▒█▒   ",
"   ███   ",
"   ▒█▒   ",
"         ",
]